### ISSUE TITLE
Review Pls

### ISSUE THREAD

**Issue by tautropfli** [bash/ico-builder#1]

**Comment by tautropfli** [comment]
@janhohenheim

**Comment by janhohenheim** [comment]
- [x] Derive `Deref` and `DerefMut` for `IconSizes` and remove the `.0` from `sizes.0`
- [x] IMO [these lines](https://github.com/bash/ico-builder/blob/main/src/lib.rs#L108-L114) violate the SRP and should be in their own function
- [x] Replace the `PathBuf::push` call with `let output_path: PathBuf = [out_dir, file_name].iter().collect();`, see [the docs](https://doc.rust-lang.org/std/path/struct.PathBuf.html)
- [x] Replace the `.unwrap` calls with `.expect` with a nice message
- [x] Rename `buf` to `buffer`
- [x] Move the example in the docs to an actual example
- [x] What happens when the input images are not squares?
- [x] Reduce code duplication by making `add_source_file` call `add_source_files`
- [x] ~~`IconSizes::new` requires `'static` input, limiting its usefulness in e.g. GUIs with user input. It uses a `Cow` internally, so this is unnecessary~~

**Comment by tautropfli** [comment]
Thaaanks so much for your review ❤️. You indeed caught some things I have missed :)

I have addressed most of the comments and checked them off the list.

> Derive `Deref` and `DerefMut` for `IconSizes` and remove the `.0` from `sizes.0`.

I can only implement `Deref` as my underlying Cow might be a non-mutable reference :)

> * `IconSizes::new` requires `'static` input, limiting its usefulness in e.g. GUIs with user input. It uses a `Cow` internally, so this is unnecessary

I only need the `Cow` so that I can create `IconSizes` in const contexts. In that case `'static` is indeed required.

If you have non-static data, you can use this `From` impl:
```rust
impl<'a, I> From<I> for IconSizes
where
    I: IntoIterator<Item = &'a u32>
```

**Comment by janhohenheim** [comment]
Aaah I see, fair enough. Consider the review finished in that case :)

**Comment by tautropfli** [comment]
Oh, I forgot to close this :) Thanks again for the review ❤
